# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:/tools/Maya/Tapp/Maya/modelling/resources/dialog.ui'
#
# Created: Mon Jul 13 14:58:55 2015
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(256, 616)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.line_8 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_7.addWidget(self.line_8)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.line_9 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_9.sizePolicy().hasHeightForWidth())
        self.line_9.setSizePolicy(sizePolicy)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_7.addWidget(self.line_9)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.detachSeparate_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detachSeparate_pushButton.sizePolicy().hasHeightForWidth())
        self.detachSeparate_pushButton.setSizePolicy(sizePolicy)
        self.detachSeparate_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.detachSeparate_pushButton.setFont(font)
        self.detachSeparate_pushButton.setObjectName("detachSeparate_pushButton")
        self.verticalLayout.addWidget(self.detachSeparate_pushButton)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scatter_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scatter_pushButton.sizePolicy().hasHeightForWidth())
        self.scatter_pushButton.setSizePolicy(sizePolicy)
        self.scatter_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scatter_pushButton.setFont(font)
        self.scatter_pushButton.setObjectName("scatter_pushButton")
        self.gridLayout_2.addWidget(self.scatter_pushButton, 0, 0, 1, 1)
        self.scatterInfo_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scatterInfo_pushButton.sizePolicy().hasHeightForWidth())
        self.scatterInfo_pushButton.setSizePolicy(sizePolicy)
        self.scatterInfo_pushButton.setMinimumSize(QtCore.QSize(30, 25))
        self.scatterInfo_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.scatterInfo_pushButton.setObjectName("scatterInfo_pushButton")
        self.gridLayout_2.addWidget(self.scatterInfo_pushButton, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.uvDeluxe_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uvDeluxe_pushButton.sizePolicy().hasHeightForWidth())
        self.uvDeluxe_pushButton.setSizePolicy(sizePolicy)
        self.uvDeluxe_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.uvDeluxe_pushButton.setFont(font)
        self.uvDeluxe_pushButton.setObjectName("uvDeluxe_pushButton")
        self.verticalLayout.addWidget(self.uvDeluxe_pushButton)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.line_12 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_12.sizePolicy().hasHeightForWidth())
        self.line_12.setSizePolicy(sizePolicy)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_9.addWidget(self.line_12)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.line_13 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_13.sizePolicy().hasHeightForWidth())
        self.line_13.setSizePolicy(sizePolicy)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_9.addWidget(self.line_13)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.symmetry_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symmetry_pushButton.sizePolicy().hasHeightForWidth())
        self.symmetry_pushButton.setSizePolicy(sizePolicy)
        self.symmetry_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.symmetry_pushButton.setFont(font)
        self.symmetry_pushButton.setObjectName("symmetry_pushButton")
        self.verticalLayout.addWidget(self.symmetry_pushButton)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.line_10 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_10.sizePolicy().hasHeightForWidth())
        self.line_10.setSizePolicy(sizePolicy)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_8.addWidget(self.line_10)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.line_11 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_11.sizePolicy().hasHeightForWidth())
        self.line_11.setSizePolicy(sizePolicy)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_8.addWidget(self.line_11)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mirrorBlendshape_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mirrorBlendshape_pushButton.sizePolicy().hasHeightForWidth())
        self.mirrorBlendshape_pushButton.setSizePolicy(sizePolicy)
        self.mirrorBlendshape_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mirrorBlendshape_pushButton.setFont(font)
        self.mirrorBlendshape_pushButton.setObjectName("mirrorBlendshape_pushButton")
        self.horizontalLayout_3.addWidget(self.mirrorBlendshape_pushButton)
        self.UVSymmetry_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UVSymmetry_pushButton.sizePolicy().hasHeightForWidth())
        self.UVSymmetry_pushButton.setSizePolicy(sizePolicy)
        self.UVSymmetry_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UVSymmetry_pushButton.setFont(font)
        self.UVSymmetry_pushButton.setObjectName("UVSymmetry_pushButton")
        self.horizontalLayout_3.addWidget(self.UVSymmetry_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.line_4 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_5.addWidget(self.line_4)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_5.addWidget(self.line_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.loadPositionVerts_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadPositionVerts_pushButton.sizePolicy().hasHeightForWidth())
        self.loadPositionVerts_pushButton.setSizePolicy(sizePolicy)
        self.loadPositionVerts_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.loadPositionVerts_pushButton.setObjectName("loadPositionVerts_pushButton")
        self.gridLayout.addWidget(self.loadPositionVerts_pushButton, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 1, 1, 1)
        self.positionVerts_label = QtGui.QLabel(self.centralwidget)
        self.positionVerts_label.setAlignment(QtCore.Qt.AlignCenter)
        self.positionVerts_label.setObjectName("positionVerts_label")
        self.gridLayout.addWidget(self.positionVerts_label, 0, 2, 1, 1)
        self.loadUpVert_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadUpVert_pushButton.sizePolicy().hasHeightForWidth())
        self.loadUpVert_pushButton.setSizePolicy(sizePolicy)
        self.loadUpVert_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.loadUpVert_pushButton.setObjectName("loadUpVert_pushButton")
        self.gridLayout.addWidget(self.loadUpVert_pushButton, 1, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 1, 1, 1)
        self.upVert_label = QtGui.QLabel(self.centralwidget)
        self.upVert_label.setAlignment(QtCore.Qt.AlignCenter)
        self.upVert_label.setObjectName("upVert_label")
        self.gridLayout.addWidget(self.upVert_label, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.locator_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.locator_checkBox.setEnabled(True)
        self.locator_checkBox.setChecked(False)
        self.locator_checkBox.setObjectName("locator_checkBox")
        self.horizontalLayout.addWidget(self.locator_checkBox)
        self.mesh_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.mesh_checkBox.setEnabled(True)
        self.mesh_checkBox.setChecked(False)
        self.mesh_checkBox.setObjectName("mesh_checkBox")
        self.horizontalLayout.addWidget(self.mesh_checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.create_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_pushButton.sizePolicy().hasHeightForWidth())
        self.create_pushButton.setSizePolicy(sizePolicy)
        self.create_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create_pushButton.setFont(font)
        self.create_pushButton.setObjectName("create_pushButton")
        self.verticalLayout.addWidget(self.create_pushButton)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_6 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_6.addWidget(self.line_6)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_6.addWidget(self.line_7)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.roadkill_useLSCM_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.roadkill_useLSCM_checkBox.setObjectName("roadkill_useLSCM_checkBox")
        self.horizontalLayout_2.addWidget(self.roadkill_useLSCM_checkBox)
        self.roadkill_dontFillHoles_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.roadkill_dontFillHoles_checkBox.setObjectName("roadkill_dontFillHoles_checkBox")
        self.horizontalLayout_2.addWidget(self.roadkill_dontFillHoles_checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.roadkill_liveUnwrap_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.roadkill_liveUnwrap_checkBox.setObjectName("roadkill_liveUnwrap_checkBox")
        self.verticalLayout.addWidget(self.roadkill_liveUnwrap_checkBox)
        self.roadKill_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roadKill_pushButton.sizePolicy().hasHeightForWidth())
        self.roadKill_pushButton.setSizePolicy(sizePolicy)
        self.roadKill_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.roadKill_pushButton.setFont(font)
        self.roadKill_pushButton.setObjectName("roadKill_pushButton")
        self.verticalLayout.addWidget(self.roadKill_pushButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tapp Modelling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.detachSeparate_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Detach/Separate", None, QtGui.QApplication.UnicodeUTF8))
        self.scatter_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Scatter", None, QtGui.QApplication.UnicodeUTF8))
        self.scatterInfo_pushButton.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.uvDeluxe_pushButton.setText(QtGui.QApplication.translate("MainWindow", "UV Deluxe", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "UV-Destructive", None, QtGui.QApplication.UnicodeUTF8))
        self.symmetry_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Symmetry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "UV-Preserving", None, QtGui.QApplication.UnicodeUTF8))
        self.mirrorBlendshape_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Select all blendshapes first, then the original mesh last!</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.mirrorBlendshape_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Mirror Blendshape", None, QtGui.QApplication.UnicodeUTF8))
        self.UVSymmetry_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Select the edited mesh first, then the original mesh last!</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.UVSymmetry_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Symmetry", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Triangulate Pivot", None, QtGui.QApplication.UnicodeUTF8))
        self.loadPositionVerts_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Load Position Verts", None, QtGui.QApplication.UnicodeUTF8))
        self.positionVerts_label.setText(QtGui.QApplication.translate("MainWindow", "No Position Verts loaded!", None, QtGui.QApplication.UnicodeUTF8))
        self.loadUpVert_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Load Upvector Vert", None, QtGui.QApplication.UnicodeUTF8))
        self.upVert_label.setText(QtGui.QApplication.translate("MainWindow", "No Upvector Vert loaded!", None, QtGui.QApplication.UnicodeUTF8))
        self.locator_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Create Locator", None, QtGui.QApplication.UnicodeUTF8))
        self.mesh_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Change Mesh Pivot", None, QtGui.QApplication.UnicodeUTF8))
        self.create_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "RoadKill", None, QtGui.QApplication.UnicodeUTF8))
        self.roadkill_useLSCM_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Use LSCM", None, QtGui.QApplication.UnicodeUTF8))
        self.roadkill_dontFillHoles_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Don\'t Fill Holes", None, QtGui.QApplication.UnicodeUTF8))
        self.roadkill_liveUnwrap_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Live Unwrap", None, QtGui.QApplication.UnicodeUTF8))
        self.roadKill_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Unwrap", None, QtGui.QApplication.UnicodeUTF8))

