# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/tokejepsen/Documents/GitHub/Tapp/Maya/rigging/resources/dialog.ui'
#
# Created: Tue Apr 15 22:33:21 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(178, 213)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.central_verticalLayout = QtGui.QVBoxLayout()
        self.central_verticalLayout.setObjectName("central_verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.doraSkin_pushButton = QtGui.QPushButton(self.centralwidget)
        self.doraSkin_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.doraSkin_pushButton.setObjectName("doraSkin_pushButton")
        self.horizontalLayout_4.addWidget(self.doraSkin_pushButton)
        self.ngSkinTools_pushButton = QtGui.QPushButton(self.centralwidget)
        self.ngSkinTools_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.ngSkinTools_pushButton.setObjectName("ngSkinTools_pushButton")
        self.horizontalLayout_4.addWidget(self.ngSkinTools_pushButton)
        self.central_verticalLayout.addLayout(self.horizontalLayout_4)
        self.sculptInbetweenEditor_pushButton = QtGui.QPushButton(self.centralwidget)
        self.sculptInbetweenEditor_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.sculptInbetweenEditor_pushButton.setObjectName("sculptInbetweenEditor_pushButton")
        self.central_verticalLayout.addWidget(self.sculptInbetweenEditor_pushButton)
        self.zvRadialBlendshape_pushButton = QtGui.QPushButton(self.centralwidget)
        self.zvRadialBlendshape_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.zvRadialBlendshape_pushButton.setObjectName("zvRadialBlendshape_pushButton")
        self.central_verticalLayout.addWidget(self.zvRadialBlendshape_pushButton)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_3.addWidget(self.line_3)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_3.addWidget(self.line_4)
        self.central_verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cylinderPreviewCreate_pushButton = QtGui.QPushButton(self.centralwidget)
        self.cylinderPreviewCreate_pushButton.setObjectName("cylinderPreviewCreate_pushButton")
        self.horizontalLayout_5.addWidget(self.cylinderPreviewCreate_pushButton)
        self.cylinderPreviewDelete_pushButton = QtGui.QPushButton(self.centralwidget)
        self.cylinderPreviewDelete_pushButton.setObjectName("cylinderPreviewDelete_pushButton")
        self.horizontalLayout_5.addWidget(self.cylinderPreviewDelete_pushButton)
        self.central_verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.central_verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.latticeAdd_pushButton = QtGui.QPushButton(self.centralwidget)
        self.latticeAdd_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.latticeAdd_pushButton.setObjectName("latticeAdd_pushButton")
        self.horizontalLayout_2.addWidget(self.latticeAdd_pushButton)
        self.latticeRemove_pushButton = QtGui.QPushButton(self.centralwidget)
        self.latticeRemove_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.latticeRemove_pushButton.setObjectName("latticeRemove_pushButton")
        self.horizontalLayout_2.addWidget(self.latticeRemove_pushButton)
        self.central_verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.central_verticalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.doraSkin_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Dora Skin", None, QtGui.QApplication.UnicodeUTF8))
        self.ngSkinTools_pushButton.setText(QtGui.QApplication.translate("MainWindow", "ngSkinTools", None, QtGui.QApplication.UnicodeUTF8))
        self.sculptInbetweenEditor_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Sculpt Inbetween Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.zvRadialBlendshape_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Zv Radial Blendshape", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Cylinder Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.cylinderPreviewCreate_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.cylinderPreviewDelete_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Lattice", None, QtGui.QApplication.UnicodeUTF8))
        self.latticeAdd_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.latticeRemove_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))

