# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/toke.jepsen/Documents/GitHub/Tapp\Tapp\Maya\animation\resources/dialog.ui'
#
# Created: Thu Nov 21 14:35:10 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(316, 528)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tatTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tatTabWidget.setObjectName("tatTabWidget")
        self.characterTab = QtGui.QWidget()
        self.characterTab.setObjectName("characterTab")
        self.verticalLayout = QtGui.QVBoxLayout(self.characterTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_23 = QtGui.QFrame(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_23.sizePolicy().hasHeightForWidth())
        self.line_23.setSizePolicy(sizePolicy)
        self.line_23.setFrameShape(QtGui.QFrame.HLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.horizontalLayout_2.addWidget(self.line_23)
        self.character_fkik_label = QtGui.QLabel(self.characterTab)
        self.character_fkik_label.setObjectName("character_fkik_label")
        self.horizontalLayout_2.addWidget(self.character_fkik_label)
        self.line_2 = QtGui.QFrame(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.character_fk_pushButton = QtGui.QPushButton(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_fk_pushButton.sizePolicy().hasHeightForWidth())
        self.character_fk_pushButton.setSizePolicy(sizePolicy)
        self.character_fk_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.character_fk_pushButton.setFont(font)
        self.character_fk_pushButton.setObjectName("character_fk_pushButton")
        self.horizontalLayout.addWidget(self.character_fk_pushButton)
        self.character_ik_pushButton = QtGui.QPushButton(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_ik_pushButton.sizePolicy().hasHeightForWidth())
        self.character_ik_pushButton.setSizePolicy(sizePolicy)
        self.character_ik_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.character_ik_pushButton.setFont(font)
        self.character_ik_pushButton.setObjectName("character_ik_pushButton")
        self.horizontalLayout.addWidget(self.character_ik_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.character_range_checkBox = QtGui.QCheckBox(self.characterTab)
        self.character_range_checkBox.setObjectName("character_range_checkBox")
        self.horizontalLayout_26.addWidget(self.character_range_checkBox)
        self.character_getTimeline_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_getTimeline_pushButton.setObjectName("character_getTimeline_pushButton")
        self.horizontalLayout_26.addWidget(self.character_getTimeline_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.character_start_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_start_pushButton.setObjectName("character_start_pushButton")
        self.horizontalLayout_7.addWidget(self.character_start_pushButton)
        self.character_start_lineEdit = QtGui.QLineEdit(self.characterTab)
        self.character_start_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.character_start_lineEdit.setObjectName("character_start_lineEdit")
        self.horizontalLayout_7.addWidget(self.character_start_lineEdit)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.character_end_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_end_pushButton.setObjectName("character_end_pushButton")
        self.horizontalLayout_13.addWidget(self.character_end_pushButton)
        self.character_end_lineEdit = QtGui.QLineEdit(self.characterTab)
        self.character_end_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.character_end_lineEdit.setObjectName("character_end_lineEdit")
        self.horizontalLayout_13.addWidget(self.character_end_lineEdit)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.line_21 = QtGui.QFrame(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_21.sizePolicy().hasHeightForWidth())
        self.line_21.setSizePolicy(sizePolicy)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.horizontalLayout_8.addWidget(self.line_21)
        self.character_zerocontrols_label = QtGui.QLabel(self.characterTab)
        self.character_zerocontrols_label.setObjectName("character_zerocontrols_label")
        self.horizontalLayout_8.addWidget(self.character_zerocontrols_label)
        self.line_4 = QtGui.QFrame(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_8.addWidget(self.line_4)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.character_zerocontrol_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_zerocontrol_pushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_zerocontrol_pushButton.sizePolicy().hasHeightForWidth())
        self.character_zerocontrol_pushButton.setSizePolicy(sizePolicy)
        self.character_zerocontrol_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.character_zerocontrol_pushButton.setFont(font)
        self.character_zerocontrol_pushButton.setObjectName("character_zerocontrol_pushButton")
        self.horizontalLayout_3.addWidget(self.character_zerocontrol_pushButton)
        self.character_zerolimb_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_zerolimb_pushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_zerolimb_pushButton.sizePolicy().hasHeightForWidth())
        self.character_zerolimb_pushButton.setSizePolicy(sizePolicy)
        self.character_zerolimb_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.character_zerolimb_pushButton.setFont(font)
        self.character_zerolimb_pushButton.setObjectName("character_zerolimb_pushButton")
        self.horizontalLayout_3.addWidget(self.character_zerolimb_pushButton)
        self.character_zerocharacter_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_zerocharacter_pushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_zerocharacter_pushButton.sizePolicy().hasHeightForWidth())
        self.character_zerocharacter_pushButton.setSizePolicy(sizePolicy)
        self.character_zerocharacter_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.character_zerocharacter_pushButton.setFont(font)
        self.character_zerocharacter_pushButton.setObjectName("character_zerocharacter_pushButton")
        self.horizontalLayout_3.addWidget(self.character_zerocharacter_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.line_20 = QtGui.QFrame(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_20.sizePolicy().hasHeightForWidth())
        self.line_20.setSizePolicy(sizePolicy)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.horizontalLayout_9.addWidget(self.line_20)
        self.character_keycontrols_pushButton = QtGui.QLabel(self.characterTab)
        self.character_keycontrols_pushButton.setObjectName("character_keycontrols_pushButton")
        self.horizontalLayout_9.addWidget(self.character_keycontrols_pushButton)
        self.line_8 = QtGui.QFrame(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_9.addWidget(self.line_8)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.character_keylimb_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_keylimb_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_keylimb_pushButton.sizePolicy().hasHeightForWidth())
        self.character_keylimb_pushButton.setSizePolicy(sizePolicy)
        self.character_keylimb_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.character_keylimb_pushButton.setFont(font)
        self.character_keylimb_pushButton.setObjectName("character_keylimb_pushButton")
        self.horizontalLayout_15.addWidget(self.character_keylimb_pushButton)
        self.character_keycharacter_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_keycharacter_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_keycharacter_pushButton.sizePolicy().hasHeightForWidth())
        self.character_keycharacter_pushButton.setSizePolicy(sizePolicy)
        self.character_keycharacter_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.character_keycharacter_pushButton.setFont(font)
        self.character_keycharacter_pushButton.setObjectName("character_keycharacter_pushButton")
        self.horizontalLayout_15.addWidget(self.character_keycharacter_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.line_19 = QtGui.QFrame(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_19.sizePolicy().hasHeightForWidth())
        self.line_19.setSizePolicy(sizePolicy)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.horizontalLayout_10.addWidget(self.line_19)
        self.character_selectcontrols_pushButton = QtGui.QLabel(self.characterTab)
        self.character_selectcontrols_pushButton.setObjectName("character_selectcontrols_pushButton")
        self.horizontalLayout_10.addWidget(self.character_selectcontrols_pushButton)
        self.line_5 = QtGui.QFrame(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_10.addWidget(self.line_5)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.character_selectlimb_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_selectlimb_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_selectlimb_pushButton.sizePolicy().hasHeightForWidth())
        self.character_selectlimb_pushButton.setSizePolicy(sizePolicy)
        self.character_selectlimb_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.character_selectlimb_pushButton.setFont(font)
        self.character_selectlimb_pushButton.setObjectName("character_selectlimb_pushButton")
        self.horizontalLayout_4.addWidget(self.character_selectlimb_pushButton)
        self.character_selectcharacter_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_selectcharacter_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_selectcharacter_pushButton.sizePolicy().hasHeightForWidth())
        self.character_selectcharacter_pushButton.setSizePolicy(sizePolicy)
        self.character_selectcharacter_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.character_selectcharacter_pushButton.setFont(font)
        self.character_selectcharacter_pushButton.setObjectName("character_selectcharacter_pushButton")
        self.horizontalLayout_4.addWidget(self.character_selectcharacter_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.line_18 = QtGui.QFrame(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_18.sizePolicy().hasHeightForWidth())
        self.line_18.setSizePolicy(sizePolicy)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.horizontalLayout_11.addWidget(self.line_18)
        self.character_flippose_label = QtGui.QLabel(self.characterTab)
        self.character_flippose_label.setObjectName("character_flippose_label")
        self.horizontalLayout_11.addWidget(self.character_flippose_label)
        self.line_6 = QtGui.QFrame(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_11.addWidget(self.line_6)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.character_fliplimb_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_fliplimb_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_fliplimb_pushButton.sizePolicy().hasHeightForWidth())
        self.character_fliplimb_pushButton.setSizePolicy(sizePolicy)
        self.character_fliplimb_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.character_fliplimb_pushButton.setFont(font)
        self.character_fliplimb_pushButton.setObjectName("character_fliplimb_pushButton")
        self.horizontalLayout_5.addWidget(self.character_fliplimb_pushButton)
        self.character_flipcharacter_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_flipcharacter_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_flipcharacter_pushButton.sizePolicy().hasHeightForWidth())
        self.character_flipcharacter_pushButton.setSizePolicy(sizePolicy)
        self.character_flipcharacter_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.character_flipcharacter_pushButton.setFont(font)
        self.character_flipcharacter_pushButton.setObjectName("character_flipcharacter_pushButton")
        self.horizontalLayout_5.addWidget(self.character_flipcharacter_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.line_17 = QtGui.QFrame(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_17.sizePolicy().hasHeightForWidth())
        self.line_17.setSizePolicy(sizePolicy)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.horizontalLayout_12.addWidget(self.line_17)
        self.character_mirrorpose_label = QtGui.QLabel(self.characterTab)
        self.character_mirrorpose_label.setObjectName("character_mirrorpose_label")
        self.horizontalLayout_12.addWidget(self.character_mirrorpose_label)
        self.line_7 = QtGui.QFrame(self.characterTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_12.addWidget(self.line_7)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.character_mirrorlimb_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_mirrorlimb_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_mirrorlimb_pushButton.sizePolicy().hasHeightForWidth())
        self.character_mirrorlimb_pushButton.setSizePolicy(sizePolicy)
        self.character_mirrorlimb_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.character_mirrorlimb_pushButton.setFont(font)
        self.character_mirrorlimb_pushButton.setCheckable(False)
        self.character_mirrorlimb_pushButton.setObjectName("character_mirrorlimb_pushButton")
        self.horizontalLayout_6.addWidget(self.character_mirrorlimb_pushButton)
        self.character_mirrorcharacter_pushButton = QtGui.QPushButton(self.characterTab)
        self.character_mirrorcharacter_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_mirrorcharacter_pushButton.sizePolicy().hasHeightForWidth())
        self.character_mirrorcharacter_pushButton.setSizePolicy(sizePolicy)
        self.character_mirrorcharacter_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.character_mirrorcharacter_pushButton.setFont(font)
        self.character_mirrorcharacter_pushButton.setObjectName("character_mirrorcharacter_pushButton")
        self.horizontalLayout_6.addWidget(self.character_mirrorcharacter_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tatTabWidget.addTab(self.characterTab, "")
        self.toolsTab = QtGui.QWidget()
        self.toolsTab.setObjectName("toolsTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.toolsTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.tools_zvparentmaster_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_zvparentmaster_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_zvparentmaster_pushButton.setSizePolicy(sizePolicy)
        self.tools_zvparentmaster_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.tools_zvparentmaster_pushButton.setObjectName("tools_zvparentmaster_pushButton")
        self.horizontalLayout_16.addWidget(self.tools_zvparentmaster_pushButton)
        self.zvChain_pushButton = QtGui.QPushButton(self.toolsTab)
        self.zvChain_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.zvChain_pushButton.setObjectName("zvChain_pushButton")
        self.horizontalLayout_16.addWidget(self.zvChain_pushButton)
        self.line_9 = QtGui.QFrame(self.toolsTab)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_16.addWidget(self.line_9)
        self.tools_zvparentmasterhelp_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_zvparentmasterhelp_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_zvparentmasterhelp_pushButton.setSizePolicy(sizePolicy)
        self.tools_zvparentmasterhelp_pushButton.setMinimumSize(QtCore.QSize(30, 35))
        self.tools_zvparentmasterhelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.tools_zvparentmasterhelp_pushButton.setObjectName("tools_zvparentmasterhelp_pushButton")
        self.horizontalLayout_16.addWidget(self.tools_zvparentmasterhelp_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.tools_breakdowndragger_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_breakdowndragger_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_breakdowndragger_pushButton.setSizePolicy(sizePolicy)
        self.tools_breakdowndragger_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.tools_breakdowndragger_pushButton.setObjectName("tools_breakdowndragger_pushButton")
        self.horizontalLayout_18.addWidget(self.tools_breakdowndragger_pushButton)
        self.line_11 = QtGui.QFrame(self.toolsTab)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_18.addWidget(self.line_11)
        self.tools_breakdowndraggerhelp_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_breakdowndraggerhelp_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_breakdowndraggerhelp_pushButton.setSizePolicy(sizePolicy)
        self.tools_breakdowndraggerhelp_pushButton.setMinimumSize(QtCore.QSize(30, 35))
        self.tools_breakdowndraggerhelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.tools_breakdowndraggerhelp_pushButton.setObjectName("tools_breakdowndraggerhelp_pushButton")
        self.horizontalLayout_18.addWidget(self.tools_breakdowndraggerhelp_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.tools_holdkey_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_holdkey_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_holdkey_pushButton.setSizePolicy(sizePolicy)
        self.tools_holdkey_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.tools_holdkey_pushButton.setObjectName("tools_holdkey_pushButton")
        self.horizontalLayout_19.addWidget(self.tools_holdkey_pushButton)
        self.line_12 = QtGui.QFrame(self.toolsTab)
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_19.addWidget(self.line_12)
        self.tools_holdkeyhelp_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_holdkeyhelp_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_holdkeyhelp_pushButton.setSizePolicy(sizePolicy)
        self.tools_holdkeyhelp_pushButton.setMinimumSize(QtCore.QSize(30, 35))
        self.tools_holdkeyhelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.tools_holdkeyhelp_pushButton.setObjectName("tools_holdkeyhelp_pushButton")
        self.horizontalLayout_19.addWidget(self.tools_holdkeyhelp_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.tools_keyvaluedragger_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_keyvaluedragger_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_keyvaluedragger_pushButton.setSizePolicy(sizePolicy)
        self.tools_keyvaluedragger_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.tools_keyvaluedragger_pushButton.setObjectName("tools_keyvaluedragger_pushButton")
        self.horizontalLayout_20.addWidget(self.tools_keyvaluedragger_pushButton)
        self.line_13 = QtGui.QFrame(self.toolsTab)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_20.addWidget(self.line_13)
        self.tools_keyvaluedraggerhelp_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_keyvaluedraggerhelp_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_keyvaluedraggerhelp_pushButton.setSizePolicy(sizePolicy)
        self.tools_keyvaluedraggerhelp_pushButton.setMinimumSize(QtCore.QSize(30, 35))
        self.tools_keyvaluedraggerhelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.tools_keyvaluedraggerhelp_pushButton.setObjectName("tools_keyvaluedraggerhelp_pushButton")
        self.horizontalLayout_20.addWidget(self.tools_keyvaluedraggerhelp_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.tools_keycleanup_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_keycleanup_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_keycleanup_pushButton.setSizePolicy(sizePolicy)
        self.tools_keycleanup_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.tools_keycleanup_pushButton.setObjectName("tools_keycleanup_pushButton")
        self.horizontalLayout_17.addWidget(self.tools_keycleanup_pushButton)
        self.line_25 = QtGui.QFrame(self.toolsTab)
        self.line_25.setFrameShape(QtGui.QFrame.VLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.horizontalLayout_17.addWidget(self.line_25)
        self.tools_keycleanuphelp_pushButton = QtGui.QPushButton(self.toolsTab)
        self.tools_keycleanuphelp_pushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_keycleanuphelp_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_keycleanuphelp_pushButton.setSizePolicy(sizePolicy)
        self.tools_keycleanuphelp_pushButton.setMinimumSize(QtCore.QSize(30, 35))
        self.tools_keycleanuphelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.tools_keycleanuphelp_pushButton.setObjectName("tools_keycleanuphelp_pushButton")
        self.horizontalLayout_17.addWidget(self.tools_keycleanuphelp_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.tools_changeRotationOrder_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_changeRotationOrder_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_changeRotationOrder_pushButton.setSizePolicy(sizePolicy)
        self.tools_changeRotationOrder_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.tools_changeRotationOrder_pushButton.setObjectName("tools_changeRotationOrder_pushButton")
        self.horizontalLayout_21.addWidget(self.tools_changeRotationOrder_pushButton)
        self.tools_changeRotationOrder_comboBox = QtGui.QComboBox(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_changeRotationOrder_comboBox.sizePolicy().hasHeightForWidth())
        self.tools_changeRotationOrder_comboBox.setSizePolicy(sizePolicy)
        self.tools_changeRotationOrder_comboBox.setMinimumSize(QtCore.QSize(0, 35))
        self.tools_changeRotationOrder_comboBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tools_changeRotationOrder_comboBox.setObjectName("tools_changeRotationOrder_comboBox")
        self.tools_changeRotationOrder_comboBox.addItem("")
        self.tools_changeRotationOrder_comboBox.addItem("")
        self.tools_changeRotationOrder_comboBox.addItem("")
        self.tools_changeRotationOrder_comboBox.addItem("")
        self.tools_changeRotationOrder_comboBox.addItem("")
        self.tools_changeRotationOrder_comboBox.addItem("")
        self.horizontalLayout_21.addWidget(self.tools_changeRotationOrder_comboBox)
        self.line_26 = QtGui.QFrame(self.toolsTab)
        self.line_26.setFrameShape(QtGui.QFrame.VLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.horizontalLayout_21.addWidget(self.line_26)
        self.tools_changeRotationOrderHelp_pushButton = QtGui.QPushButton(self.toolsTab)
        self.tools_changeRotationOrderHelp_pushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_changeRotationOrderHelp_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_changeRotationOrderHelp_pushButton.setSizePolicy(sizePolicy)
        self.tools_changeRotationOrderHelp_pushButton.setMinimumSize(QtCore.QSize(30, 35))
        self.tools_changeRotationOrderHelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.tools_changeRotationOrderHelp_pushButton.setObjectName("tools_changeRotationOrderHelp_pushButton")
        self.horizontalLayout_21.addWidget(self.tools_changeRotationOrderHelp_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.tools_ghosting_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_ghosting_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_ghosting_pushButton.setSizePolicy(sizePolicy)
        self.tools_ghosting_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.tools_ghosting_pushButton.setObjectName("tools_ghosting_pushButton")
        self.horizontalLayout_23.addWidget(self.tools_ghosting_pushButton)
        self.line_27 = QtGui.QFrame(self.toolsTab)
        self.line_27.setFrameShape(QtGui.QFrame.VLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.horizontalLayout_23.addWidget(self.line_27)
        self.tools_ghostingHelp_pushButton = QtGui.QPushButton(self.toolsTab)
        self.tools_ghostingHelp_pushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_ghostingHelp_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_ghostingHelp_pushButton.setSizePolicy(sizePolicy)
        self.tools_ghostingHelp_pushButton.setMinimumSize(QtCore.QSize(30, 35))
        self.tools_ghostingHelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.tools_ghostingHelp_pushButton.setObjectName("tools_ghostingHelp_pushButton")
        self.horizontalLayout_23.addWidget(self.tools_ghostingHelp_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.tools_localizeImagePlane_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_localizeImagePlane_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_localizeImagePlane_pushButton.setSizePolicy(sizePolicy)
        self.tools_localizeImagePlane_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.tools_localizeImagePlane_pushButton.setObjectName("tools_localizeImagePlane_pushButton")
        self.verticalLayout_2.addWidget(self.tools_localizeImagePlane_pushButton)
        self.tools_rat_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_rat_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_rat_pushButton.setSizePolicy(sizePolicy)
        self.tools_rat_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.tools_rat_pushButton.setObjectName("tools_rat_pushButton")
        self.verticalLayout_2.addWidget(self.tools_rat_pushButton)
        self.tools_paie_pushButton = QtGui.QPushButton(self.toolsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_paie_pushButton.sizePolicy().hasHeightForWidth())
        self.tools_paie_pushButton.setSizePolicy(sizePolicy)
        self.tools_paie_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.tools_paie_pushButton.setObjectName("tools_paie_pushButton")
        self.verticalLayout_2.addWidget(self.tools_paie_pushButton)
        self.collisionDeformer_pushButton = QtGui.QPushButton(self.toolsTab)
        self.collisionDeformer_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.collisionDeformer_pushButton.setObjectName("collisionDeformer_pushButton")
        self.verticalLayout_2.addWidget(self.collisionDeformer_pushButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tatTabWidget.addTab(self.toolsTab, "")
        self.verticalLayout_3.addWidget(self.tatTabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tatTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.character_fkik_label.setText(QtGui.QApplication.translate("MainWindow", "FK - IK Switching", None, QtGui.QApplication.UnicodeUTF8))
        self.character_fk_pushButton.setText(QtGui.QApplication.translate("MainWindow", "FK", None, QtGui.QApplication.UnicodeUTF8))
        self.character_ik_pushButton.setText(QtGui.QApplication.translate("MainWindow", "IK", None, QtGui.QApplication.UnicodeUTF8))
        self.character_range_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.character_getTimeline_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Get Timeline Info", None, QtGui.QApplication.UnicodeUTF8))
        self.character_start_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.character_end_pushButton.setText(QtGui.QApplication.translate("MainWindow", "End:", None, QtGui.QApplication.UnicodeUTF8))
        self.character_zerocontrols_label.setText(QtGui.QApplication.translate("MainWindow", "Zero Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.character_zerocontrol_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.character_zerolimb_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Limb", None, QtGui.QApplication.UnicodeUTF8))
        self.character_zerocharacter_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.character_keycontrols_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Key Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.character_keylimb_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Limb", None, QtGui.QApplication.UnicodeUTF8))
        self.character_keycharacter_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.character_selectcontrols_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Select Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.character_selectlimb_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Limb", None, QtGui.QApplication.UnicodeUTF8))
        self.character_selectcharacter_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.character_flippose_label.setText(QtGui.QApplication.translate("MainWindow", "Flip Pose", None, QtGui.QApplication.UnicodeUTF8))
        self.character_fliplimb_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Limb", None, QtGui.QApplication.UnicodeUTF8))
        self.character_flipcharacter_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.character_mirrorpose_label.setText(QtGui.QApplication.translate("MainWindow", "Mirror Pose", None, QtGui.QApplication.UnicodeUTF8))
        self.character_mirrorlimb_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Limb", None, QtGui.QApplication.UnicodeUTF8))
        self.character_mirrorcharacter_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.tatTabWidget.setTabText(self.tatTabWidget.indexOf(self.characterTab), QtGui.QApplication.translate("MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_zvparentmaster_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Zv Parent Master", None, QtGui.QApplication.UnicodeUTF8))
        self.zvChain_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Zv Chain", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_zvparentmasterhelp_pushButton.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_breakdowndragger_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Breakdown Dragger", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_breakdowndraggerhelp_pushButton.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_holdkey_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Hold Key", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_holdkeyhelp_pushButton.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_keyvaluedragger_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Key Value Dragger", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_keyvaluedraggerhelp_pushButton.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_keycleanup_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Key Clean Up", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_keycleanuphelp_pushButton.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_changeRotationOrder_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Change Rotation Order", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_changeRotationOrder_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "xyz", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_changeRotationOrder_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "yzx", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_changeRotationOrder_comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "zxy", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_changeRotationOrder_comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "xzy", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_changeRotationOrder_comboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "yxz", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_changeRotationOrder_comboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "zyx", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_changeRotationOrderHelp_pushButton.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_ghosting_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Ghosting", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_ghostingHelp_pushButton.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_localizeImagePlane_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Localize Image Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_rat_pushButton.setText(QtGui.QApplication.translate("MainWindow", "RAT", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_paie_pushButton.setText(QtGui.QApplication.translate("MainWindow", "PAIE", None, QtGui.QApplication.UnicodeUTF8))
        self.collisionDeformer_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Collision Deformer", None, QtGui.QApplication.UnicodeUTF8))
        self.tatTabWidget.setTabText(self.tatTabWidget.indexOf(self.toolsTab), QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))

