# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/GitHub/Tapp/Maya/lighting/resources/dialog.ui'
#
# Created: Thu Sep 11 21:48:34 2014
#      by: pyside-uic 0.2.15 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(251, 523)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_3 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_6.addWidget(self.line_3)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.addRimLight_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addRimLight_pushButton.sizePolicy().hasHeightForWidth())
        self.addRimLight_pushButton.setSizePolicy(sizePolicy)
        self.addRimLight_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.addRimLight_pushButton.setFont(font)
        self.addRimLight_pushButton.setObjectName("addRimLight_pushButton")
        self.verticalLayout.addWidget(self.addRimLight_pushButton)
        self.fileTextureManager_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTextureManager_pushButton.sizePolicy().hasHeightForWidth())
        self.fileTextureManager_pushButton.setSizePolicy(sizePolicy)
        self.fileTextureManager_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.fileTextureManager_pushButton.setFont(font)
        self.fileTextureManager_pushButton.setObjectName("fileTextureManager_pushButton")
        self.verticalLayout.addWidget(self.fileTextureManager_pushButton)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.line_9 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_9.sizePolicy().hasHeightForWidth())
        self.line_9.setSizePolicy(sizePolicy)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_9.addWidget(self.line_9)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.line_10 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_10.sizePolicy().hasHeightForWidth())
        self.line_10.setSizePolicy(sizePolicy)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_9.addWidget(self.line_10)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.fgshooter_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgshooter_pushButton.sizePolicy().hasHeightForWidth())
        self.fgshooter_pushButton.setSizePolicy(sizePolicy)
        self.fgshooter_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.fgshooter_pushButton.setFont(font)
        self.fgshooter_pushButton.setObjectName("fgshooter_pushButton")
        self.verticalLayout.addWidget(self.fgshooter_pushButton)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.line = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.exportAlembic_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportAlembic_pushButton.sizePolicy().hasHeightForWidth())
        self.exportAlembic_pushButton.setSizePolicy(sizePolicy)
        self.exportAlembic_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.exportAlembic_pushButton.setFont(font)
        self.exportAlembic_pushButton.setObjectName("exportAlembic_pushButton")
        self.horizontalLayout_4.addWidget(self.exportAlembic_pushButton)
        self.importAlembic_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importAlembic_pushButton.sizePolicy().hasHeightForWidth())
        self.importAlembic_pushButton.setSizePolicy(sizePolicy)
        self.importAlembic_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.importAlembic_pushButton.setFont(font)
        self.importAlembic_pushButton.setObjectName("importAlembic_pushButton")
        self.horizontalLayout_4.addWidget(self.importAlembic_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.connectAlembic_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectAlembic_pushButton.sizePolicy().hasHeightForWidth())
        self.connectAlembic_pushButton.setSizePolicy(sizePolicy)
        self.connectAlembic_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.connectAlembic_pushButton.setFont(font)
        self.connectAlembic_pushButton.setObjectName("connectAlembic_pushButton")
        self.horizontalLayout_10.addWidget(self.connectAlembic_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.line_7 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_8.addWidget(self.line_7)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.line_8 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_8.addWidget(self.line_8)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.arnoldSubdivision_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arnoldSubdivision_pushButton.sizePolicy().hasHeightForWidth())
        self.arnoldSubdivision_pushButton.setSizePolicy(sizePolicy)
        self.arnoldSubdivision_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.arnoldSubdivision_pushButton.setFont(font)
        self.arnoldSubdivision_pushButton.setObjectName("arnoldSubdivision_pushButton")
        self.horizontalLayout_3.addWidget(self.arnoldSubdivision_pushButton)
        self.arnoldSubdivision_spinBox = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arnoldSubdivision_spinBox.sizePolicy().hasHeightForWidth())
        self.arnoldSubdivision_spinBox.setSizePolicy(sizePolicy)
        self.arnoldSubdivision_spinBox.setProperty("value", 2)
        self.arnoldSubdivision_spinBox.setObjectName("arnoldSubdivision_spinBox")
        self.horizontalLayout_3.addWidget(self.arnoldSubdivision_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.arnoldMask_pushButton = QtGui.QPushButton(self.centralwidget)
        self.arnoldMask_pushButton.setObjectName("arnoldMask_pushButton")
        self.horizontalLayout_11.addWidget(self.arnoldMask_pushButton)
        self.arnoldRebuildMask_pushButton = QtGui.QPushButton(self.centralwidget)
        self.arnoldRebuildMask_pushButton.setObjectName("arnoldRebuildMask_pushButton")
        self.horizontalLayout_11.addWidget(self.arnoldRebuildMask_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.line_5 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_7.addWidget(self.line_5)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_7.addWidget(self.line_6)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.addSubdivision_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addSubdivision_pushButton.sizePolicy().hasHeightForWidth())
        self.addSubdivision_pushButton.setSizePolicy(sizePolicy)
        self.addSubdivision_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.addSubdivision_pushButton.setFont(font)
        self.addSubdivision_pushButton.setObjectName("addSubdivision_pushButton")
        self.verticalLayout.addWidget(self.addSubdivision_pushButton)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.setSubdivision_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setSubdivision_pushButton.sizePolicy().hasHeightForWidth())
        self.setSubdivision_pushButton.setSizePolicy(sizePolicy)
        self.setSubdivision_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.setSubdivision_pushButton.setFont(font)
        self.setSubdivision_pushButton.setObjectName("setSubdivision_pushButton")
        self.horizontalLayout.addWidget(self.setSubdivision_pushButton)
        self.subdivision_spinBox = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subdivision_spinBox.sizePolicy().hasHeightForWidth())
        self.subdivision_spinBox.setSizePolicy(sizePolicy)
        self.subdivision_spinBox.setProperty("value", 4)
        self.subdivision_spinBox.setObjectName("subdivision_spinBox")
        self.horizontalLayout.addWidget(self.subdivision_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addDomeLight_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addDomeLight_pushButton.sizePolicy().hasHeightForWidth())
        self.addDomeLight_pushButton.setSizePolicy(sizePolicy)
        self.addDomeLight_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.addDomeLight_pushButton.setFont(font)
        self.addDomeLight_pushButton.setObjectName("addDomeLight_pushButton")
        self.horizontalLayout_2.addWidget(self.addDomeLight_pushButton)
        self.domeLightCameraSpace_checkBox = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domeLightCameraSpace_checkBox.sizePolicy().hasHeightForWidth())
        self.domeLightCameraSpace_checkBox.setSizePolicy(sizePolicy)
        self.domeLightCameraSpace_checkBox.setObjectName("domeLightCameraSpace_checkBox")
        self.horizontalLayout_2.addWidget(self.domeLightCameraSpace_checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.createTechPasses_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createTechPasses_pushButton.sizePolicy().hasHeightForWidth())
        self.createTechPasses_pushButton.setSizePolicy(sizePolicy)
        self.createTechPasses_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.createTechPasses_pushButton.setFont(font)
        self.createTechPasses_pushButton.setObjectName("createTechPasses_pushButton")
        self.verticalLayout.addWidget(self.createTechPasses_pushButton)
        self.addObjectID_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addObjectID_pushButton.sizePolicy().hasHeightForWidth())
        self.addObjectID_pushButton.setSizePolicy(sizePolicy)
        self.addObjectID_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.addObjectID_pushButton.setFont(font)
        self.addObjectID_pushButton.setObjectName("addObjectID_pushButton")
        self.verticalLayout.addWidget(self.addObjectID_pushButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tapp Lighting", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.addRimLight_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Add Rim Light", None, QtGui.QApplication.UnicodeUTF8))
        self.fileTextureManager_pushButton.setText(QtGui.QApplication.translate("MainWindow", "File Texture Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Mental Ray", None, QtGui.QApplication.UnicodeUTF8))
        self.fgshooter_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Fgshooter", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Alembic", None, QtGui.QApplication.UnicodeUTF8))
        self.exportAlembic_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Export Alembic", None, QtGui.QApplication.UnicodeUTF8))
        self.importAlembic_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Import Alembic", None, QtGui.QApplication.UnicodeUTF8))
        self.connectAlembic_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Connect Alembic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Arnold", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldSubdivision_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Set Subdivision", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldMask_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Makes the selection into a AOV rgb mask.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldMask_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Mask", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldRebuildMask_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Rebuilds the AOV rgb mask from the current sets.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldRebuildMask_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Rebuild Masks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Vray", None, QtGui.QApplication.UnicodeUTF8))
        self.addSubdivision_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Add Subdivision", None, QtGui.QApplication.UnicodeUTF8))
        self.setSubdivision_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Set Subdivision", None, QtGui.QApplication.UnicodeUTF8))
        self.addDomeLight_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Add Dome Light", None, QtGui.QApplication.UnicodeUTF8))
        self.domeLightCameraSpace_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Camera Space", None, QtGui.QApplication.UnicodeUTF8))
        self.createTechPasses_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Create Tech Passes", None, QtGui.QApplication.UnicodeUTF8))
        self.addObjectID_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Add Object ID", None, QtGui.QApplication.UnicodeUTF8))

