# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/toke.jepsen/Documents/GitHub/Tapp\Tapp\Maya\animation\character\resources/dialog.ui'
#
# Created: Fri Nov 29 15:33:05 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(292, 466)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_23 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_23.sizePolicy().hasHeightForWidth())
        self.line_23.setSizePolicy(sizePolicy)
        self.line_23.setFrameShape(QtGui.QFrame.HLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.horizontalLayout_2.addWidget(self.line_23)
        self.character_fkik_label = QtGui.QLabel(self.centralwidget)
        self.character_fkik_label.setObjectName("character_fkik_label")
        self.horizontalLayout_2.addWidget(self.character_fkik_label)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fk_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fk_pushButton.sizePolicy().hasHeightForWidth())
        self.fk_pushButton.setSizePolicy(sizePolicy)
        self.fk_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fk_pushButton.setFont(font)
        self.fk_pushButton.setObjectName("fk_pushButton")
        self.horizontalLayout.addWidget(self.fk_pushButton)
        self.ik_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ik_pushButton.sizePolicy().hasHeightForWidth())
        self.ik_pushButton.setSizePolicy(sizePolicy)
        self.ik_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ik_pushButton.setFont(font)
        self.ik_pushButton.setObjectName("ik_pushButton")
        self.horizontalLayout.addWidget(self.ik_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.range_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.range_checkBox.setObjectName("range_checkBox")
        self.horizontalLayout_26.addWidget(self.range_checkBox)
        self.getTimeline_pushButton = QtGui.QPushButton(self.centralwidget)
        self.getTimeline_pushButton.setObjectName("getTimeline_pushButton")
        self.horizontalLayout_26.addWidget(self.getTimeline_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.start_pushButton = QtGui.QPushButton(self.centralwidget)
        self.start_pushButton.setObjectName("start_pushButton")
        self.horizontalLayout_7.addWidget(self.start_pushButton)
        self.start_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.start_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.start_lineEdit.setObjectName("start_lineEdit")
        self.horizontalLayout_7.addWidget(self.start_lineEdit)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.end_pushButton = QtGui.QPushButton(self.centralwidget)
        self.end_pushButton.setObjectName("end_pushButton")
        self.horizontalLayout_13.addWidget(self.end_pushButton)
        self.end_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.end_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.end_lineEdit.setObjectName("end_lineEdit")
        self.horizontalLayout_13.addWidget(self.end_lineEdit)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.line_21 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_21.sizePolicy().hasHeightForWidth())
        self.line_21.setSizePolicy(sizePolicy)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.horizontalLayout_8.addWidget(self.line_21)
        self.character_zerocontrols_label = QtGui.QLabel(self.centralwidget)
        self.character_zerocontrols_label.setObjectName("character_zerocontrols_label")
        self.horizontalLayout_8.addWidget(self.character_zerocontrols_label)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_8.addWidget(self.line_4)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.zeroControl_pushButton = QtGui.QPushButton(self.centralwidget)
        self.zeroControl_pushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zeroControl_pushButton.sizePolicy().hasHeightForWidth())
        self.zeroControl_pushButton.setSizePolicy(sizePolicy)
        self.zeroControl_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.zeroControl_pushButton.setFont(font)
        self.zeroControl_pushButton.setObjectName("zeroControl_pushButton")
        self.horizontalLayout_3.addWidget(self.zeroControl_pushButton)
        self.zeroLimb_pushButton = QtGui.QPushButton(self.centralwidget)
        self.zeroLimb_pushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zeroLimb_pushButton.sizePolicy().hasHeightForWidth())
        self.zeroLimb_pushButton.setSizePolicy(sizePolicy)
        self.zeroLimb_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.zeroLimb_pushButton.setFont(font)
        self.zeroLimb_pushButton.setObjectName("zeroLimb_pushButton")
        self.horizontalLayout_3.addWidget(self.zeroLimb_pushButton)
        self.zeroCharacter_pushButton = QtGui.QPushButton(self.centralwidget)
        self.zeroCharacter_pushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zeroCharacter_pushButton.sizePolicy().hasHeightForWidth())
        self.zeroCharacter_pushButton.setSizePolicy(sizePolicy)
        self.zeroCharacter_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.zeroCharacter_pushButton.setFont(font)
        self.zeroCharacter_pushButton.setObjectName("zeroCharacter_pushButton")
        self.horizontalLayout_3.addWidget(self.zeroCharacter_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.line_20 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_20.sizePolicy().hasHeightForWidth())
        self.line_20.setSizePolicy(sizePolicy)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.horizontalLayout_9.addWidget(self.line_20)
        self.character_keycontrols_pushButton = QtGui.QLabel(self.centralwidget)
        self.character_keycontrols_pushButton.setObjectName("character_keycontrols_pushButton")
        self.horizontalLayout_9.addWidget(self.character_keycontrols_pushButton)
        self.line_8 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_9.addWidget(self.line_8)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.keyLimb_pushButton = QtGui.QPushButton(self.centralwidget)
        self.keyLimb_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyLimb_pushButton.sizePolicy().hasHeightForWidth())
        self.keyLimb_pushButton.setSizePolicy(sizePolicy)
        self.keyLimb_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.keyLimb_pushButton.setFont(font)
        self.keyLimb_pushButton.setObjectName("keyLimb_pushButton")
        self.horizontalLayout_15.addWidget(self.keyLimb_pushButton)
        self.keyCharacter_pushButton = QtGui.QPushButton(self.centralwidget)
        self.keyCharacter_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyCharacter_pushButton.sizePolicy().hasHeightForWidth())
        self.keyCharacter_pushButton.setSizePolicy(sizePolicy)
        self.keyCharacter_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.keyCharacter_pushButton.setFont(font)
        self.keyCharacter_pushButton.setObjectName("keyCharacter_pushButton")
        self.horizontalLayout_15.addWidget(self.keyCharacter_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.line_19 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_19.sizePolicy().hasHeightForWidth())
        self.line_19.setSizePolicy(sizePolicy)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.horizontalLayout_10.addWidget(self.line_19)
        self.character_selectcontrols_pushButton = QtGui.QLabel(self.centralwidget)
        self.character_selectcontrols_pushButton.setObjectName("character_selectcontrols_pushButton")
        self.horizontalLayout_10.addWidget(self.character_selectcontrols_pushButton)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_10.addWidget(self.line_5)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.selectLimb_pushButton = QtGui.QPushButton(self.centralwidget)
        self.selectLimb_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectLimb_pushButton.sizePolicy().hasHeightForWidth())
        self.selectLimb_pushButton.setSizePolicy(sizePolicy)
        self.selectLimb_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectLimb_pushButton.setFont(font)
        self.selectLimb_pushButton.setObjectName("selectLimb_pushButton")
        self.horizontalLayout_4.addWidget(self.selectLimb_pushButton)
        self.selectCharacter_pushButton = QtGui.QPushButton(self.centralwidget)
        self.selectCharacter_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectCharacter_pushButton.sizePolicy().hasHeightForWidth())
        self.selectCharacter_pushButton.setSizePolicy(sizePolicy)
        self.selectCharacter_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.selectCharacter_pushButton.setFont(font)
        self.selectCharacter_pushButton.setObjectName("selectCharacter_pushButton")
        self.horizontalLayout_4.addWidget(self.selectCharacter_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.line_18 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_18.sizePolicy().hasHeightForWidth())
        self.line_18.setSizePolicy(sizePolicy)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.horizontalLayout_11.addWidget(self.line_18)
        self.character_flippose_label = QtGui.QLabel(self.centralwidget)
        self.character_flippose_label.setObjectName("character_flippose_label")
        self.horizontalLayout_11.addWidget(self.character_flippose_label)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_11.addWidget(self.line_6)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.flipLimb_pushButton = QtGui.QPushButton(self.centralwidget)
        self.flipLimb_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flipLimb_pushButton.sizePolicy().hasHeightForWidth())
        self.flipLimb_pushButton.setSizePolicy(sizePolicy)
        self.flipLimb_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.flipLimb_pushButton.setFont(font)
        self.flipLimb_pushButton.setObjectName("flipLimb_pushButton")
        self.horizontalLayout_5.addWidget(self.flipLimb_pushButton)
        self.flipCharacter_pushButton = QtGui.QPushButton(self.centralwidget)
        self.flipCharacter_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flipCharacter_pushButton.sizePolicy().hasHeightForWidth())
        self.flipCharacter_pushButton.setSizePolicy(sizePolicy)
        self.flipCharacter_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.flipCharacter_pushButton.setFont(font)
        self.flipCharacter_pushButton.setObjectName("flipCharacter_pushButton")
        self.horizontalLayout_5.addWidget(self.flipCharacter_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.line_17 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_17.sizePolicy().hasHeightForWidth())
        self.line_17.setSizePolicy(sizePolicy)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.horizontalLayout_12.addWidget(self.line_17)
        self.character_mirrorpose_label = QtGui.QLabel(self.centralwidget)
        self.character_mirrorpose_label.setObjectName("character_mirrorpose_label")
        self.horizontalLayout_12.addWidget(self.character_mirrorpose_label)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_12.addWidget(self.line_7)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.mirrorLimb_pushButton = QtGui.QPushButton(self.centralwidget)
        self.mirrorLimb_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mirrorLimb_pushButton.sizePolicy().hasHeightForWidth())
        self.mirrorLimb_pushButton.setSizePolicy(sizePolicy)
        self.mirrorLimb_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mirrorLimb_pushButton.setFont(font)
        self.mirrorLimb_pushButton.setCheckable(False)
        self.mirrorLimb_pushButton.setObjectName("mirrorLimb_pushButton")
        self.horizontalLayout_6.addWidget(self.mirrorLimb_pushButton)
        self.mirrorCharacter_pushButton = QtGui.QPushButton(self.centralwidget)
        self.mirrorCharacter_pushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mirrorCharacter_pushButton.sizePolicy().hasHeightForWidth())
        self.mirrorCharacter_pushButton.setSizePolicy(sizePolicy)
        self.mirrorCharacter_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mirrorCharacter_pushButton.setFont(font)
        self.mirrorCharacter_pushButton.setObjectName("mirrorCharacter_pushButton")
        self.horizontalLayout_6.addWidget(self.mirrorCharacter_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.character_fkik_label.setText(QtGui.QApplication.translate("MainWindow", "FK - IK Switching", None, QtGui.QApplication.UnicodeUTF8))
        self.fk_pushButton.setText(QtGui.QApplication.translate("MainWindow", "FK", None, QtGui.QApplication.UnicodeUTF8))
        self.ik_pushButton.setText(QtGui.QApplication.translate("MainWindow", "IK", None, QtGui.QApplication.UnicodeUTF8))
        self.range_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.getTimeline_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Get Timeline Info", None, QtGui.QApplication.UnicodeUTF8))
        self.start_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.end_pushButton.setText(QtGui.QApplication.translate("MainWindow", "End:", None, QtGui.QApplication.UnicodeUTF8))
        self.character_zerocontrols_label.setText(QtGui.QApplication.translate("MainWindow", "Zero Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.zeroControl_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.zeroLimb_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Limb", None, QtGui.QApplication.UnicodeUTF8))
        self.zeroCharacter_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.character_keycontrols_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Key Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.keyLimb_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Limb", None, QtGui.QApplication.UnicodeUTF8))
        self.keyCharacter_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.character_selectcontrols_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Select Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.selectLimb_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Limb", None, QtGui.QApplication.UnicodeUTF8))
        self.selectCharacter_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.character_flippose_label.setText(QtGui.QApplication.translate("MainWindow", "Flip Pose", None, QtGui.QApplication.UnicodeUTF8))
        self.flipLimb_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Limb", None, QtGui.QApplication.UnicodeUTF8))
        self.flipCharacter_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.character_mirrorpose_label.setText(QtGui.QApplication.translate("MainWindow", "Mirror Pose", None, QtGui.QApplication.UnicodeUTF8))
        self.mirrorLimb_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Limb", None, QtGui.QApplication.UnicodeUTF8))
        self.mirrorCharacter_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))

