# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/tokejepsen/Documents/GitHub/Tapp/Maya/playblastQueue/resources/dialog.ui'
#
# Created: Sun May 25 20:58:49 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 530)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.width_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.width_spinBox.setMinimum(1)
        self.width_spinBox.setMaximum(999999)
        self.width_spinBox.setProperty("value", 1920)
        self.width_spinBox.setObjectName("width_spinBox")
        self.horizontalLayout.addWidget(self.width_spinBox)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(8, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.height_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.height_spinBox.setMinimum(1)
        self.height_spinBox.setMaximum(999999)
        self.height_spinBox.setProperty("value", 1080)
        self.height_spinBox.setObjectName("height_spinBox")
        self.horizontalLayout.addWidget(self.height_spinBox)
        self.add_pushButton = QtGui.QPushButton(self.centralwidget)
        self.add_pushButton.setObjectName("add_pushButton")
        self.horizontalLayout.addWidget(self.add_pushButton)
        self.remove_pushButton = QtGui.QPushButton(self.centralwidget)
        self.remove_pushButton.setObjectName("remove_pushButton")
        self.horizontalLayout.addWidget(self.remove_pushButton)
        self.export_pushButton = QtGui.QPushButton(self.centralwidget)
        self.export_pushButton.setObjectName("export_pushButton")
        self.horizontalLayout.addWidget(self.export_pushButton)
        self.import_pushButton = QtGui.QPushButton(self.centralwidget)
        self.import_pushButton.setObjectName("import_pushButton")
        self.horizontalLayout.addWidget(self.import_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outputFolder_pushButton = QtGui.QPushButton(self.centralwidget)
        self.outputFolder_pushButton.setObjectName("outputFolder_pushButton")
        self.horizontalLayout_2.addWidget(self.outputFolder_pushButton)
        self.outputFolder_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.outputFolder_lineEdit.setObjectName("outputFolder_lineEdit")
        self.horizontalLayout_2.addWidget(self.outputFolder_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.playblastQueue_pushButton = QtGui.QPushButton(self.centralwidget)
        self.playblastQueue_pushButton.setObjectName("playblastQueue_pushButton")
        self.verticalLayout.addWidget(self.playblastQueue_pushButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Playblast Queue", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.add_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.export_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.import_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>If output folder is not specified, the playblasts will be saved in the same folder as each Maya file.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.outputFolder_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Output folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.playblastQueue_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Playblast Queue", None, QtGui.QApplication.UnicodeUTF8))

